### ISSUE TITLE
Ycmd error: ycm_core library compiled for Python 2 but loaded in Python 3.

### ISSUE THREAD

**Issue by zijianyue** [abingham/emacs-ycmd#331] opened 2016-08-12 04:08 UTC
I sometimes encounter this error ,but I have uninstalled Python3, and set the command like this:
(set-variable 'ycmd-server-command '("c:/Python27/python.exe" "-u" "D:/ycmd/ycmd/")), then what's the problem?  I'm working on WIN7 64bit, python2.7.12 is installed in c:/Python27/. LLVM 3.8.1

**Comment by abingham** [comment] 2016-08-12 07:11
When you say "sometimes" do you mean that it works sometimes and breaks sometimes with no other associated changes? That would be really strange.

What happens if you run the command on the command line?

**Comment by zijianyue** [comment] 2016-08-12 12:09
yes ,it can work OK most of the time, but sometimes break

**Comment by zijianyue** [comment] 2016-08-12 12:10
I enabled the log ,my include paths are ok, no error found in the log

**Comment by abingham** [comment] 2016-08-12 12:26
But what happens if you run ycmd on the command line using the same arguments as in ycmd-server-command?

**Comment by zijianyue** [comment] 2016-08-13 02:22
Sorry, I don't know how to do as you asked. I made an example to reproduce it, can you use this to check the problem? I just use ycmd-goto ,ycmd-get-type, ycmd-parse-buffer, and the error happened sometimes.
https://github.com/zijianyue/test-ycmd.git
And my dotemacs file is here
https://github.com/zijianyue/my-init/blob/master/.emacs , you can search "ycmd" in my init file.

**Comment by zijianyue** [comment] 2016-08-18 07:13
The python cache in third-party folder is compiled using python3 ,when I use a python2 version ycm_core.pyd, it reports this error

**Comment by ptrv** [comment] 2016-08-18 08:41
@zijianyue I am glad you could resolve the issue

**Comment by ZzAntares** [comment] 2016-09-03 00:22
Hi @zijianyue could you elaborate more on that? I'm having the same issue, which folder/cache I need to remove?

**Comment by zijianyue** [comment] 2016-09-03 07:10
@ZzAntares ,sorry ,this issue on my machine is still exist.

**Comment by ptrv** [comment] 2016-09-03 22:35
@ZzAntares The issue is that the python version that you use in Emacs is different from the one that you used to compiled your `ycmd` server.

You can fix the error by making sure that the version that you use for compileng the server is the same you set with the `ycmd-server-command` variable.

**Comment by ptrv** [comment] 2016-09-03 22:36
Closing the issue since the python version mismatch is not an `emacs-ycmd` issue.

**Closed by ptrv** 2016-09-03 22:36 UTC
