### ISSUE TITLE
Error when set `ycmd-force-semantic-completion` to `t`.

### ISSUE THREAD

**Issue by Yevgnen** [abingham/emacs-ycmd#286] opened 2016-03-21 11:28 UTC
Hi,

I use virtualenv in my project and I set `ycmd-python-binary-path` to the python I wish to use in my project. Even that I found ycmd will not complete symbols that in classes I wrote. So I set `ycmd-force-semantic-completion` to `t` and ycmd now give me candidates that I expected. But the following error happen quite often and was displayed in the minibuffer. Even though the completion is not interrupted but annoys me much. So, is this an issue of this project or just an issue of `company` ? I'm sorry to bother you again but any help will be appreciated !

    Company: An error occurred in post-command
    Company: frontend company-pseudo-tooltip-frontend error "Args out of range: " [statement: 
            self.eigvals = eigvals]", 0, 60" on command post-command
    Saving file /Users/user/code/prml/example/Ch12 - Principal Component Analysis/pca.py...
    Wrote /Users/user/code/prml/example/Ch12 - Principal Component Analysis/pca.py
    Company: An error occurred in post-command
    Company: frontend company-pseudo-tooltip-frontend error "Wrong type argument: arrayp, nil" on command post-command
    Company: An error occurred in post-command
    Company: frontend company-pseudo-tooltip-frontend error "Wrong type argument: arrayp, nil" on command post-command
    Company: An error occurred in post-command

By the way, I find that the melpa version of `emacs-ycmd` does not contain things like `ycmd-eldoc.el`. Maybe the recipe

    (ycmd :fetcher github
          :repo "abingham/emacs-ycmd"
          :files ("ycmd.el" "third-party/*.el" "contrib/*.el"))

should be modified ?

**Comment by ptrv** [comment] 2016-03-21 14:02
From first sight it looks like the issue is in `company-mode` but it is probably that `company-ycmd` is using some bad values.

Since I cannot reproduce the issue, could you post some reproduction steps?

Regarding `ycmd-eldoc`, I guess it should have an own recipe and not part of the `emacs-ycmd` one, like `company-ycmd` or `flycheck-ycmd`

**Comment by Yevgnen** [comment] 2016-03-21 14:30
I'm trying to find out what' going on and find the reproduction steps... May I ask a question ? Is it possible to let ycmd launch different python servers for each virtualenv project ?

**Comment by ptrv** [comment] 2016-03-21 14:37
> I'm trying to find out what' going on and find the reproduction steps...

Great!

> Is it possible to let ycmd launch different python servers for each virtualenv project ?

Right now it is not possible to launch multiple servers at the same time.

**Comment by Yevgnen** [comment] 2016-03-21 15:25
Now I find something odd.

I take some minimal configs for test.

    (require 'package)
    
    (setq package-archives '(("marmalade" . "http://marmalade-repo.org/packages/")
                             ("gnu" . "http://elpa.gnu.org/packages/")
                             ("melpa" . "https://melpa.org/packages/")
                             ("org" . "http://orgmode.org/elpa/")))
    
    (package-initialize)
    
    (unless (and (file-exists-p (expand-file-name "elpa/archives/marmalade" user-emacs-directory))
                 (file-exists-p (expand-file-name "elpa/archives/gnu" user-emacs-directory))
                 (file-exists-p (expand-file-name "elpa/archives/melpa" user-emacs-directory))
                 (file-exists-p (expand-file-name "elpa/archives/org" user-emacs-directory)))
      (package-refresh-contents))
    
    (unless (package-installed-p 'use-package)
      (package-refresh-contents)
      (package-install 'use-package))
    
    (use-package company
      :ensure t
      :diminish company-mode
      :init
      (setq company-idle-delay 0.1          ;; point 1
            company-tooltip-align-annotations t ;; point 2
            company-frontends '(company-pseudo-tooltip-frontend))
    
      :config
      (global-company-mode 1)
    
      (use-package company-ycmd
        :ensure t
        :init
        (defvar venv-location "~/.env")     ; This variable is originally in package virtualenvwrapper
    
        (use-package ycmd
          :ensure t
          :init
          (setq ycmd-server-command '("/usr/local/bin/python3" "/usr/local/ycmd/ycmd")
                ycmd-global-config "~/.ycmd_global_conf.py"
                ycmd-force-semantic-completion t)
    
          (defun ycmd//use-virtualenv ()
            (hack-local-variables)
            (when (boundp 'project-venv-name)
              (setq ycmd-python-binary-path
                    (expand-file-name "python" (expand-file-name "bin" (expand-file-name project-venv-name venv-location))))))
    
          (add-hook 'python-mode-hook
                    #'(lambda ()
                        (set (make-local-variable 'company-backends)
                             '(company-ycmd))))
          (add-hook 'python-mode-hook #'ycmd-mode)
          (add-hook 'python-mode-hook #'ycmd//use-virtualenv)
    
          :config
          (global-ycmd-mode 1))))
    

Found two issues, about `company-idle-delay` and `company-tooltip-align-annotations`.

First, if `company-idle-delay` is set to `0.1` and `company-tooltip-align-annotations` is set to `t`, then type

    from scipy import random as sprd
    sprd.[rand]

wait for the menu popup and select the candidate should reproduce the issue.

Second, if `company-idle-delay` is set to `0.1` and `company-tooltip-align-annotations` is set to `nil`, then type as mentioned above,  the minibuffer output something like 

    deferred error : (args-out-of-range "" 0 -3)
    deferred error : (args-out-of-range #("sp" 0 2 (fontified t)) 0 -3)

Third,  if `company-idle-delay` is set to `1` and `company-tooltip-align-annotations` is set to `t`, the issue is the same as the second one. (Meaning that a large delay is independent of the annotation issue.)

Forth, if `comany-idle-delay` is set to `0.2` and `company-tooltip-align-annotations` is set to `nil`, then everything seems go well.

There are two conclusion here. First, I think `0.1` may too small(not sure) for `company` and `ycmd` as I see the request log of `ycmd` seem the server is a bit slow sometimes. Second, there's something wrong with the annotation part. Maybe be its a company issue since the the first and second errors telling that `args-out-of-range`, or maybe `ycmd` pass some wrong values(lack of args?) to it. I've not figure out which one it is yet.

**Comment by Yevgnen** [comment] 2016-03-21 15:34
By the way, the `python` build-in module(sys, path etc.) seems not have this issue. I don't know why.

**Comment by ptrv** [comment] 2016-03-21 15:37
Thanks for you investigations. I'll try to do the reproduction steps myself as soon as I have time.

I have already seen a similar error to this already but could not reproduce:

```
deferred error : (args-out-of-range "" 0 -3)
deferred error : (args-out-of-range #("sp" 0 2 (fontified t)) 0 -3)
```

**Comment by ptrv** [comment] 2016-03-21 23:31
I could reproduce this error:

```
Company: frontend company-pseudo-tooltip-unless-just-one-frontend error "Wrong type argument: arrayp, nil" on command post-command
```

with `company-tooltip-align-annotations` set to `t`,the following code (cursor at '|') and invoking semantic completion: 

``` python
from scipy import random as rnd
rnd.|
```
comment-string-strip
The problem is that some of the text we put in the annotation have some new lines in it. The `company--create-lines` function is called when creating the tooltip and it does some cleaning of the annotation string with the function `comment-string-strip` which fails to strip the leading space and returns nil. This leads to the error string mentioned above.

As a workaround we can remove the newline characters from the annotation string.

**Comment by ptrv** [comment] 2016-03-22 00:21
Ok, I did some investigation on the `deferred error : (args-out-of-range "" 0 -3)` error.

This happens when the point in buffer when the get completions request gets sent differs from the point in buffer when response comes back from server, i.e. after a completion is invoked you type some characters and then the prefix does not match anymore. This can happen more often if you have `company-idle-delay` set to a very short time because when typing fast completion requests can be sent in between.

However I could only reproduce this issue with asynchronous completion, i.e. when setting `company-ycmd-request-sync-timeout` to `0`.

We could add a check for point in buffer when invoking completion is same as in response in `company-ycmd--get-candidates-deferred`.

**Comment by Yevgnen** [comment] 2016-03-22 00:21
You find it! That's cool! I tried the workaround, the 

    Company: frontend company-pseudo-tooltip-unless-just-one-frontend error "Wrong type argument: arrayp, nil" on command post-command

error seemed disappeared. But this time I find that, with `company-tooltip-align-annotations` set to `t`, a large value(eg, 1) of `company-idle-delay` will cause things like

    deferred error : (args-out-of-range "" 0 -3)
    deferred error : (args-out-of-range #("sp" 0 2 (fontified t)) 0 -3)

You may need to type `rnd.ran`| and backspace to `.` and type several times to reproduce this. Maybe this two issue is related ? Even though that's not very likely.

**Comment by Yevgnen** [comment] 2016-03-22 00:40
Thanks for your investigation! Now things seem to go well! The `deferred error` may happened more likely when a new package is being `import`, but after that things seem fine.

**Comment by ptrv** [comment] 2016-04-10 09:39
I guess this is fixed now. Closing it. @Yevgnen reopen if the problem still exists.

**Closed by ptrv** 2016-04-10 09:39 UTC

**Comment by Yevgnen** [comment] 2016-10-25 15:51
Thanks for your work. Even though there's no error now, but the `Skip ycmd completion response [4 times]` happens quite often. Especially when the file contains a module needs quite a time to import, e.g.  `tensorflow`.

```
import numpy as np
import tensorflow as tf
tf.place
```

The cursor becomes lag as when keep typing, whether the completion is started or not. When the completion is started successfully, the above message keep altering quite often.

**Comment by ptrv** [comment] 2016-10-28 13:02
@Yevgnen If the package is big with lots of completion candidates then it can happen that completion takes a while.

We have a mechanism in place  in `company-ycmd` for getting completion synchronously (which blcoks Emacs of course) and if takes longer, then we start an asynchronous completion request which does not block Emacs. The timeout for the synchronous completion request is is 50 milliseconds. If you set the variable `company-ycmd-request-sync-timeout` to `0` then only asynchronous requests are started for completion. Can you try setting the variable to 0? It should improve the typing issue.

The message `Skip ycmd completion response` comes always when the cursor position when you started the completion request differs from the cursor position when the completion results are coming back from the `ycmd` server. This can happen if you have large package you try to get completion from.

**Comment by Yevgnen** [comment] 2016-10-30 12:11
@ptrv Thanks for your reply. `company-ycmd-request-sync-timeout` is set to `0.1` in the above reply. Setting it to `0` cause the tooltip flashes each time I type a character. And dose not reduce the `Skip ycmd completion response` message.

`company-jedi` also has a slow response in the first time of completion, but gets to normal speed after that.

**Comment by ptrv** [comment] 2016-10-31 09:42
The flashing of the popup with async completer is a known issue in `company-mode`, which is also the reason we introduced the hybrid solution to start with a synchronous request and then start an asynchronous request if it takes longer then a specified timeout.

For example, I work on a large C++ code base and have `company-ycmd-request-sync-timeout` always set to `0`.

 And if you type faster than the completion results coming back then the `Skip ycmd completion response` appears.

I don't what `company-jedi` is doing to get normal speed. But for the completion we rely on the `ycmd` server, so maybe it's worth asking in the `ycmd` project about the speed of completing `tensorflow`.

**Comment by shenxs** [comment] 2017-09-07 04:50
If I set `ycmd-force-semantic-completion` to `t` then  the completion of c++ header wouldn't work any more .Everthing else is fine.
here is my config
```

  (add-hook 'c++-mode-hook 'ycmd-mode)
  (set-variable 'ycmd-server-command '("python" "-u"  "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/"))
  (set-variable 'ycmd-global-config '"/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py")
  (add-hook 'ycmd-file-parse-result-hook 'flycheck-ycmd--cache-parse-results)
  (add-to-list 'flycheck-checker 'ycmd)
  (when (not (display-graphic-p))
    (setq flycheck-indication-mode nil))

  (require 'company-ycmd)
  (company-ycmd-setup)
  (require 'flycheck-ycmd)
  (flycheck-ycmd-setup)

  (setq ycmd-seed-identifiers-with-keywords t)
  (setq ycmd-request-message-level -1)
  (setq ycmd-force-semantic-completion t)
```
Here is the error
```
2017-09-05 15:55:00,252 - DEBUG - Global extra conf not loaded or no function YcmCorePreload
serving on http://127.0.0.1:34773
2017-09-05 15:55:03,939 - INFO - Received event notification
2017-09-05 15:55:03,939 - DEBUG - Event name: BufferVisit
2017-09-05 15:55:03,975 - INFO - Received event notification
2017-09-05 15:55:03,976 - DEBUG - Event name: FileReadyToParse
2017-09-05 15:55:03,976 - INFO - Adding buffer identifiers for file: /home/richard/hello.cpp
2017-09-05 15:55:05,830 - INFO - Received filetype completion available request
2017-09-05 15:55:05,886 - INFO - Received completion request
2017-09-05 15:55:05,886 - DEBUG - Using filetype completion: True
Traceback (most recent call last):
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 108, in wrapper
    return callback( *args, **kwargs )
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/hmac_plugin.py", line 70, in wrapper
    body = callback( *args, **kwargs )
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/handlers.py", line 103, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 217, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 233, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 113, in ComputeCandidatesInner
    raise RuntimeError( NO_COMPLETIONS_MESSAGE )
RuntimeError: No completions found; errors in the file?
2017-09-05 15:55:06,365 - INFO - Received defined subcommands request
2017-09-05 15:55:06,397 - INFO - Received command request
2017-09-05 15:55:12,102 - INFO - Received completion request
2017-09-05 15:55:12,102 - DEBUG - Using filetype completion: True
2017-09-05 15:55:12,203 - INFO - Received completion request
2017-09-05 15:55:12,203 - DEBUG - Using filetype completion: True
Traceback (most recent call last):
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 108, in wrapper
    return callback( *args, **kwargs )
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/hmac_plugin.py", line 70, in wrapper
    body = callback( *args, **kwargs )
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/handlers.py", line 103, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 217, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 233, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 95, in ComputeCandidatesInner
    raise RuntimeError( PARSING_FILE_MESSAGE )
RuntimeError: Still parsing file, no completions yet.
2017-09-05 15:55:12,427 - INFO - Received completion request
2017-09-05 15:55:12,428 - DEBUG - Using filetype completion: True
Traceback (most recent call last):
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 108, in wrapper
    return callback( *args, **kwargs )
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/hmac_plugin.py", line 70, in wrapper
    body = callback( *args, **kwargs )
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/handlers.py", line 103, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 217, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 233, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 95, in ComputeCandidatesInner
    raise RuntimeError( PARSING_FILE_MESSAGE )
RuntimeError: Still parsing file, no completions yet.
2017-09-05 15:55:12,483 - INFO - Received command request
Traceback (most recent call last):
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle/bottle.py", line 1740, in wrapper
    rv = callback(*a, **ka)
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 108, in wrapper
    return callback( *args, **kwargs )
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/hmac_plugin.py", line 70, in wrapper
    body = callback( *args, **kwargs )
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/handlers.py", line 103, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 217, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/completer.py", line 233, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/home/richard/k-vim/bundle/YouCompleteMe/third_party/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 113, in ComputeCandidatesInner
    raise RuntimeError( NO_COMPLETIONS_MESSAGE )
RuntimeError: No completions found; errors in the file?
```

**Comment by ptrv** [comment] 2017-09-07 19:15
@shenxs In `ycmd` there are multiple completers (identifier, filename and semantic) that work together in different contexts. The includes are provided by the filename completer. If you set `ycmd-force-semantic-completion` to `t` you bypass the filename completer and the result is basically what you experience. I would recommend to keep `ycmd-force-semantic-completion` set to `nil` and have a dedicated function for a forced semantic completion that you can use alongside the regular completion. (same in `YouCompleteMe` in vim)
If you use `company` you can have the following function bound to some key:
```emacs-lisp
(defun company-ycmd-semantic-complete ()
  (interactive)
  (let ((ycmd-force-semantic-completion t))
    (company-cancel)
    (company-complete)))
``` 
We set `ycmd-force-semantic-completion` to `t` only locally in this function.

**Comment by shenxs** [comment] 2017-09-08 14:58
@ptrv Thanks it just works .
