### ISSUE TITLE
Something wired happens in my spacemacs

### ISSUE THREAD

**Issue by yanjijinxiao** [abingham/emacs-ycmd#231] opened 2015-11-15 15:42 UTC
![image](https://cloud.githubusercontent.com/assets/5549530/11169412/e72ff5e8-8bf1-11e5-890c-802a9c07c679.png)
Well, as you see, this mistake always happens unless I save the buffer. So, do you have a solution about it? Thanks.

**Comment by ptrv** [comment] 2015-11-15 16:17
I cannot reproduce the issue with the code you have in the screenshot. Can you give more precise reproduction steps? For example, what part of your code is new since you save the buffer.

Can you reproduce this issue without spacemacs?

Spacemacs installs a lot of packages and maybe some of those interfere with emacs-ycmd.

**Comment by yanjijinxiao** [comment] 2015-11-15 16:45
This is the first time I use ycmd. Here are the steps.
![image](https://cloud.githubusercontent.com/assets/5549530/11169699/3e4370fa-8bfa-11e5-8d53-73eca866de46.png)
At first, code completion seems to be fine. And do not press the RETURN button to create a new line and use the single character to test the code completion function again.
![image](https://cloud.githubusercontent.com/assets/5549530/11169731/fb97f4fa-8bfa-11e5-8ded-85057ae1f1cf.png)
![image](https://cloud.githubusercontent.com/assets/5549530/11169734/07b48794-8bfb-11e5-8171-c3bfd41c8345.png)
I found I can even use a variable that I never create to get the code completions.Is it a bug?

**Comment by yanjijinxiao** [comment] 2015-11-15 16:52
Well, this issue only occurs when I create a variable using single character. It's strange, right?

**Comment by abingham** [comment] 2015-11-15 17:19
What's your value for `company-minimum-prefix-length`? If you change that value, does it affect the behavior you're seeing?

**Comment by yanjijinxiao** [comment] 2015-11-15 17:40
Its value is 2. I change it and it works. Thanks.
And I found another issue.
![image](https://cloud.githubusercontent.com/assets/5549530/11169996/3b3f8490-8c02-11e5-8d66-e5e1c5663fb1.png)
![image](https://cloud.githubusercontent.com/assets/5549530/11170022/049138d4-8c03-11e5-9e09-5d2b3f16983d.png)
I randomly type something to make flycheck works. And the error message will remain until I start a new line. Could you please help me to fix it?

**Comment by ptrv** [comment] 2015-11-15 17:42
Thanks @yanjijinxiao for the detailed steps. I could reproduce the issue now.

The issue appears when you get a valid completion list then try to complete on a single character variable.

**Comment by yanjijinxiao** [comment] 2015-11-15 17:44
The error will disappear when I start a new line or use the ycmd-parse-buffer command. And I set flycheck-idle-change-delay and ycmd-idle-change-delay to zero. So this issue really confuse me.

**Comment by yanjijinxiao** [comment] 2015-11-15 17:48
@ptrv Well, I set company-minimum-prefix-length to 1 and it works. Thanks for your attention.

**Comment by abingham** [comment] 2015-11-15 18:03
I don't think there's much we can do about the flycheck issue. It might be a problem with flycheck itself. We receive new error/warning information after ycmd parses a file, so until you get a new parse flycheck will have information from the previous build.

**Comment by ptrv** [comment] 2015-11-15 18:19
> We receive new error/warning information after ycmd parses a file, so until you get a new parse flycheck will have information from the previous build.

Exactly!

However, there is the possibility to let ycmd parse the buffer after every buffer change by adding `idle-change` to `ycmd-parse-conditions`, but it slows down emacs a bit.

**Comment by yanjijinxiao** [comment] 2015-11-15 18:23
@ptrv I've already added it. But nothing changed.
@abingham Thanks for your patience.

**Comment by yanjijinxiao** [comment] 2015-11-15 18:29
@abingham I wonder why the ycmd-parse-buffer command still works?

**Comment by ptrv** [comment] 2015-11-15 18:32
@yanjijinxiao it works for me. Try closing and opening the file again.

**Comment by yanjijinxiao** [comment] 2015-11-15 18:36
@ptrv It works for me, too. I just made small mistake. Thanks a lot.

**Closed** 2015-11-15 18:51 UTC
