### ISSUE TITLE
strange behavior of company ycmd

### ISSUE THREAD

**Issue by zhuzhongshu** [abingham/emacs-ycmd#148] opened 2015-03-01 08:11 UTC
I use company-ycmd as the backend of C and C++. While when I type character such as :: and -> ,the completion begins automatically but I can't input any character because it always reminder me of "Matching input is required". So I have to call company-ycmd manually.

**Comment by abingham** [comment] 2015-03-01 11:21
Do you see any output in the `*ycmd-server*` buffer that seems relevant? How about anything in `*Messages*`? 

Also, what is the value of `company-backends`?

**Comment by zhuzhongshu** [comment] 2015-03-01 11:32
Here is the output of *ycmd-server*

https://guides.github.com/features/mastering-markdown/
2015-03-01 19:26:43,974 - DEBUG - Global extra conf not loaded or no function YcmCorePreload
serving on http://127.0.0.1:50660
2015-03-01 19:26:44,239 - INFO - Received event notification
2015-03-01 19:26:44,240 - DEBUG - Event name: FileReadyToParse
2015-03-01 19:26:44,240 - INFO - Adding buffer identifiers for file: /home/zzs/zzsweet/src/cfamily/cpp_study/study.cpp
2015-03-01 19:26:47,211 - INFO - Received event notification
2015-03-01 19:26:47,211 - DEBUG - Event name: FileReadyToParse
2015-03-01 19:26:47,212 - INFO - Adding buffer identifiers for file: /home/zzs/zzsweet/src/cfamily/cpp_study/study.cpp
2015-03-01 19:26:48,311 - INFO - Received completion request
2015-03-01 19:26:48,311 - DEBUG - Using filetype completion: True

output of *Messages*
Contacting host: 127.0.0.1:50660
[yas] Loading for `c++-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /home/zzs/.emacs.d/elpa/yasnippet-20150212.240/snippets/c++-mode) (quote c++-mode)))!
[yas] Loading compiled snippets from /home/zzs/.emacs.d/elpa/yasnippet-20150212.240/snippets/c++-mode
[yas] Loading for `cc-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /home/zzs/.emacs.d/elpa/yasnippet-20150212.240/snippets/cc-mode) (quote cc-mode)))!
[yas] Loading compiled snippets from /home/zzs/.emacs.d/elpa/yasnippet-20150212.240/snippets/cc-mode
scroll-up-command: End of buffer [6 times]
Contacting host: 127.0.0.1:50660 [2 times]
Matching input is required [3 times]
Beginning of buffer
Mark set [2 times]
Contacting host: 127.0.0.1:50660 [3 times]

The value of company-backends is (company-ycmd company-yasnippet company-files)

**Comment by dgutov** [comment] 2015-03-01 12:36
@zhuzhongshu What's your value of `company-require-match`?

**Comment by zhuzhongshu** [comment] 2015-03-01 12:45
This value is 't' but when I set it to nil, the popup window will close no matter which key you  type.

**Comment by dgutov** [comment] 2015-03-01 12:56
Sounds about right.

And to be clear, what are the popup's contents? Take a screenshot if you can.

**Comment by zhuzhongshu** [comment] 2015-03-01 13:10
![125](https://cloud.githubusercontent.com/assets/8487906/6430856/5e006c78-c057-11e4-8f3c-acdd16fbfa60.png)

**Comment by dgutov** [comment] 2015-03-01 15:15
Nothing suspicious here, either.

Now, please update to the latest Company from MELPA, call `M-x company-diag` and post the results here. And also list all Company-related customizations included in your configuration.

**Comment by zhuzhongshu** [comment] 2015-03-02 00:20
Here is the results of company-diag

Emacs 24.4.2 (x86_64-unknown-linux-gnu) of 2015-01-01 on zzs-hd
Company 0.9.0-cvs

company-backends: (company-ycmd company-yasnippet company-files)

Used backend: company-ycmd
Prefix: ("" . t)


Completions: none


and here is my configuration of company

(add-hook 'after-init-hook 'global-company-mode)
(company-quickhelp-mode 1)
(custom-set-variables
 '(company-require-match t)             ;设置为t时，如果输入错误补全窗口不会关闭，而是提示"matching input is required"
 '(company-auto-complete nil)
 '(company-auto-complete-chars (quote ignore))
 '(company-idle-delay 0)
 ;; 由于在C++中启用输入::,.和->自动补全需要启用idle-delay并且要在company-begin-commands里设置self-insert-command。
 ;; 但是这样就会导致输入指定个字符后自动开始补全，所以要把它设置的特别大......
 '(company-minimum-prefix-length 8888)
 '(company-show-numbers t)
 '(company-tooltip-align-annotations nil)
 '(company-tooltip-minimum-width 50)
 '(company-tooltip-offset-display (quote scrollbar))
 ;; '(company-transformers (quote (company-sort-by-occurrence)))
 ;; '(company-completion-started-hook (quote ((lambda (candidate)
 ;;                                             (company-filter-candidates)))))
 '(company-backends (quote (company-capf
                            company-ispell
                            company-yasnippet
                            company-files
                            company-elisp
                            company-css
                            company-eclim
                            company-semantic
                            company-xcode
                            company-ropemacs
                            company-cmake
                            company-bbdb
                            (company-dabbrev-code company-gtags company-etags company-keywords)
                            company-oddmuse
                            company-dabbrev)))
 )
;; 定义tab键自动选择缩进/补全函数。注意补全函数不是采用company-complete系列而是采用company-other-backend，
;; 这样在当前后端没有合适的补全选项时会自动跳转到下一个后端。不会像company-complete系列命令那样强烈依赖于后端的排列顺序导致很多后端不能补全
(defun complete-and-filter ()
  (interactive)
  (company-other-backend)
  (company-filter-candidates));;启动company补全的时候自动启用过滤功能，可以部分的实现不分大小写，但也有很多弊端，暂未启用
(defun indent-or-complete ()
  (interactive)
  (if (looking-at "\\_>")
      (company-other-backend)
    (indent-according-to-mode)))
;; (defun complete-or-indent ()
;;   (interactive)
;;   (if (company-manual-begin)
;;       (company-other-backend)
;;     (indent-according-to-mode)))
(with-eval-after-load 'company
  (define-key company-mode-map (kbd "<tab>") 'indent-or-complete)
  (dotimes (i 10)
    (define-key company-active-map (vector (+ (aref (kbd "C-0") 0) i))
      `(lambda () (interactive) (company-complete-number ,i))))
  (define-key company-active-map (kbd "M-n") nil)
  (define-key company-active-map (kbd "M-p") nil)
  (define-key company-active-map (kbd "C-n") #'company-select-next)
  (define-key company-active-map (kbd "C-p") #'company-select-previous)
  (define-key company-active-map (kbd "C-s") #'company-filter-candidates)
  (define-key company-active-map (kbd "C-M-s") #'company-search-candidates)
  (define-key company-active-map (kbd "<tab>") #'company-other-backend)
  ;;下面这两个绑定是在company-template里面仍然用tab触发补全，而用M-tab跳转到下一个展开点（field）
  ;;(define-key company-template-nav-map (kbd "<tab>") #'company-other-backend)
  ;;(define-key company-template-nav-map (kbd "M-<tab>") #'company-template-forward-field)
  )


(require 'ycmd)
(ycmd-setup)
(set-variable 'ycmd-server-command '("python" "/home/zzs/ycmd/ycmd/"))
(set-variable 'ycmd-global-config "/home/zzs/ycmd/cpp/ycm/.ycm_extra_conf.py")
(set-variable 'ycmd-extra-conf-whitelist '("/home/zzs/ycmd/cpp/ycm"))

(require 'company-ycmd)
(company-ycmd-setup)
(add-hook 'c-mode-common-hook
          (lambda ()
            (set (make-local-variable 'company-backends)  (quote (company-ycmd
                                                                  company-yasnippet
                                                                  company-files)))))


Besides, I also encounter an error of "Symbol's value as variable is void: company-template-nav-map" when I update it to the latest version.

**Comment by dgutov** [comment] 2015-03-02 00:35
@zhuzhongshu It says "no completions". Did you call it from the same buffer position?

**Comment by zhuzhongshu** [comment] 2015-03-02 00:41
I call  M-x company-diag after the popup menu appears. The result seems always "no completions"

**Comment by dgutov** [comment] 2015-03-02 02:17
You can dismiss the popup first.

> Symbol's value as variable is void: company-template-nav-map

This sounds implausible. I'll need a backtrace.

**Comment by zhuzhongshu** [comment] 2015-03-02 03:23
The output remains “no”...

**Comment by abingham** [comment] 2015-03-27 19:14
@zhuzhongshu First of all, let me apologize for taking so long to look into this. I've got too much on my plate right now!

Is this still a problem for you, or has it been resolved? I've tried replicating it, but I haven't been able to do so.

**Comment by zhuzhongshu** [comment] 2015-03-29 13:31
@abingham  The problem still exits....
Here is  my company and ycmd configuration:

(add-hook 'after-init-hook 'global-company-mode)
(company-quickhelp-mode 1)
(require 'ycmd)
(ycmd-setup)
(set-variable 'ycmd-server-command '("python" "/home/zzs/ycmd/ycmd/"))
(set-variable 'ycmd-global-config "/home/zzs/ycmd/cpp/ycm/.ycm_extra_conf.py")
(set-variable 'ycmd-extra-conf-whitelist '("/home/zzs/ycmd/cpp/ycm"))

(require 'company-ycmd)
(company-ycmd-setup)
(add-hook 'c-mode-common-hook
          (lambda ()
            (set (make-local-variable 'company-backends)  (quote (company-ycmd
                                                                  ;; company-yasnippet
                                                                  ;; company-files
                                                                  )))))

**Comment by abingham** [comment] 2015-03-29 15:24
Huh. Now that I look at it, I'm also seeing behavior similar to what you describe. If I enter something like `obj->`, company will bring up a list of options. At this point, if I continue typing then company will narrow down the list of selection as expected.

However if – instead of entering more characters – I use the arrow keys to navigate the list and *then* I try entering characters, I get the `Matching input required` message for each character. 

This behavior seems to be strongly related to `company-minimum-prefix-length`. I see the behavior described above when it's set to `3`. However if I set it to `1` then typing characters seems to work naturally all of the time.

@zhuzhongshu If you set `company-minimum-prefix-length` to `1`, does everything behave as you want?

@dgutov Does this makes sense to you? Is my explanation coherent enough?

**Comment by dgutov** [comment] 2015-03-29 17:47
@abingham More or less. I can't reproduce it with `company-clang`, though (which is a handy litmus test), and `company-ycmd` is currently broken in my Emacs (master).

Here's one change you should apply just because it makes sense:

```diff
@@ -272,10 +272,7 @@
        (or (not (company-in-string-or-comment))
            (company-ycmd--in-include))
        (or (and (not (ycmd-parsing-in-progress-p))
-                (let ((triggers-re "\\.\\|->\\|::"))
-                  (if (looking-back triggers-re)
-                      (company-grab-symbol-cons triggers-re 2)
-                    (company-grab-symbol))))
+                (company-grab-symbol-cons "\\.\\|->\\|::" 2))
            'stop)))
 
 (defun company-ycmd--candidates (prefix)
```

Though, to be honest, the code looks functionally equivalent to me.

**Comment by dgutov** [comment] 2015-03-29 18:06
Anyway, I'm looking into it.

**Comment by dgutov** [comment] 2015-03-30 00:15
@abingham I haven't managed to reproduce the behavior you describe with `company-clang`, even after adding `no-cache t`. However, if I set `company-require-match` to `t`, I get the reverse behavior: after typing `->`, the popup appears but I can't continue typing (similarly to what's described in the first message here). However, navigating up or down the list allows me to type again, because that sets `company--manual-action` to t and thus switches to synchronous completion.

In short, `(setq company-require-match t)` is incompatible with `company-ycmd`, and and any other asynchronous backend that doesn't use cache. This appears to be a conceptual incompatibility: if to know the updated list of completions the backend needs to call the server, and we don't want to wait for the response (right?), at least not until the user has interacted with the popup somehow, we can't verify that the newly typed character hasn't narrowed the list of completions to nothing.

@zhuzhongshu All I can suggest at this point: change `company-require-match` back to the default.

**Comment by abingham** [comment] 2015-03-30 06:20
Ugh. This morning I updated my work machine, and now I can't replicate the bad behaviour I was seeing yesterday. In fact, company-ycmd is behaving wonderfully. I get properly updated fuzzy-completion when the candidates list is displayed, it's fast, etc., etc. I'm really puzzled now.

@dgutov I'll integrate the change you mentioned above shortly.

**Comment by zhuzhongshu** [comment] 2015-03-30 08:39
@abingham yes, if I set this variable to 1, thiestrange behavior disappears and no more problems found yet...

**Comment by zhuzhongshu** [comment] 2015-03-30 11:25
@abingham 
@dgutov 
I update all my packages to the latest version, and then the problem goes away itself. Even if I set the variable company-minimum-prefix-length  to a very large number (say 100).

**Comment by abingham** [comment] 2015-03-30 11:33
The magic of open-source development ;) 
I'll close this defect, but let me know if you run into any more problems.

**Comment by zhuzhongshu** [comment] 2015-04-02 04:26
@abingham 
Sorry to trouble you again, but it's observed that the problem appears again, even if I set `company-minimum-prefix-length` to 1.
I don't know  what's the difference between call `company-ycmd` manually and automatically, but the problem only exits in the latter case.

**Comment by dgutov** [comment] 2015-04-02 11:36
@zhuzhongshu Have you tried setting `company-require-match` back to the default value?

**Comment by zhuzhongshu** [comment] 2015-04-02 11:41
@dgutov Yes, this is a solution, while I don't think it's a good one....

**Comment by dgutov** [comment] 2015-04-02 11:50
Like I've described, it's conceptually impossible for `company-ycmd` to support the `t` value.

The other option would be to change `company-mode` to switch to synchronous interaction with the server, as soon as the popup is displayed. That will have certain performance penalty.

**Comment by zhuzhongshu** [comment] 2015-04-02 12:28
What a pity it is...

**Comment by zhuzhongshu** [comment] 2015-04-02 12:37
@dgutov  BTW, do you find the problem could appears even if  `company--manual-action` is set to `t`?  Sometimes it works well and sometimes not.

**Comment by dgutov** [comment] 2015-04-02 12:40
`company--manual-action` is an internal variable. There's no point changing its value, because it's reset to nil at the end of every completion.

But if that approach worked, that would be the second option I've mentioned above (synchronous completion, certain performance penalty).

**Comment by zhuzhongshu** [comment] 2015-04-03 05:23
OK, I set `company-ycmd-enable-fuzzy-matching` to `nil` to enables the company-mode internal cache feature.  
@dgutov Does it possible for company-mode  to provide a native "fuzzy matching" function  without disable the internal cache feature (which will not conflict with `company-require-match` feature) in the future?

**Comment by dgutov** [comment] 2015-04-03 12:11
@zhuzhongshu It could, but that still wouldn't be an equivalent of what `company-ycmd` is doing: not only it delegates fuzzy matching to the server, the results also come back pre-sorted, I'm assuming with the best matches on top. Only a language-aware matcher can do a good job with this.

I'd rather make completion synchronous is your use case than introduce this kind of complexity and duplication.

**Comment by zhuzhongshu** [comment] 2015-04-03 12:43
What I really want is the case insensitive completion (treat anapple equals to anApple) and I don't care the order of candidates (sometimes the best match may not on top).  The  synchronous  completion is very slow on my computer, so I'd rather turn off  the fuzzy matching feature.

@dgutov  @abingham 
Many thanks for you help!

**Comment by dgutov** [comment] 2015-04-03 12:47
>  The synchronous completion is very slow on my computer

How did you test it?

**Comment by zhuzhongshu** [comment] 2015-04-03 13:02
When I insert or delete characters, I can feel it's not as smooth. The difference is significant.

**Comment by dgutov** [comment] 2015-04-04 23:45
I see. Maybe we'll provide some "filter cached entries" callback, and you would be able to write your own wrapper around `company-ycmd`.

Fuzzy matching without weights is easy to implement, see here: https://github.com/emacs-mirror/emacs/blob/207f11935755236b21ca4d3fe6b19206e0a9ed33/lisp/ido.el#L3829-L3833

**Comment by abingham** [comment] 2015-04-07 07:17
I've had some time to look at this a bit this morning. On the assumption, as @dgutov suggests, that asynchronous calls are a problem, I've created a branch that uses synchronous calls (from company's point of view, at least) to get candidates from ycmd:

    https://github.com/abingham/emacs-ycmd/tree/synchronous-company

However, this doesn't appear to me to fix the basic conceptual incompatibilities. Even with synchronous calls I see the completion menu disappear/flicker with each new keypress. 

It seems, instead, that the core problem is that emacs-ycmd disables company's cache, not that it makes asynchronous calls to ycmd. 

@dgutov: Am I missing something important? Is asynchrony really a part of the problem and, if so, why do I still see issues when I fetch candidates synchronously?

@zhuzhongshu Can you try the synchronous branch and let me know if you see any improvement.

I know this is a pretty sticky defect, and I haven't had a lot of time to devote to it. Hopefully we can get it resolved to everyone's satisfaction (or at least understand it properly) soon.

**Comment by dgutov** [comment] 2015-04-07 10:22
@abingham As far as I can see, with this change, the `company-require-match t` problem is gone.

Flickering is a different issue. I'm guessing it happens because some I/O occurs during the execution of the command (triggering redisplay..?), *and* because the popup overlay is always hidden in `pre-command-hook`. The latter seems necessary, because otherwise it screws with row/column at point calculations (and there must be other commands that would be surprised to find an overlay hiding the ten lines after point).

Anyway, that's not something to fix in this package, and a different rendering method should help.

**Comment by zhuzhongshu** [comment] 2015-04-07 10:37
>> Even with synchronous calls I see the completion menu disappear/flicker with each new keypress. 

@abingham  I can reproduce this by setting `company-require-match` to `nil`.

**Comment by abingham** [comment] 2015-04-07 10:46
OK, it sounds like we can probably close this particular issue pretty soon. We might be able to just change `company-ycmd` to be synchronous all of the time, but I'm worried that this might cause problems for people working on large C++ projects.

@r4nt Can you try the `synchronous-company` branch (see above) on one of your larger llvm files? I worry that the purely synchronous mode will introduce so much blocking that `company-ycmd` will become unusable.

**Comment by dgutov** [comment] 2015-04-07 10:50
> We might be able to just change company-ycmd to be synchronous all of the time

Why? `company-require-match t` is used pretty rarely. And like @zhuzhongshu described, the completion won't work as smoothly.

**Comment by abingham** [comment] 2015-05-20 12:48
For good house-keeping I'm going to close this now. However, if anyone wants it open, the by all means re-open it.

If you do so, it might be a good idea to try to summarize the current state of the issue, at least from your point of view. As it is, it's all pretty confusing!

**Closed by abingham** 2015-05-20 12:48 UTC

**Comment by zhuzhongshu** [comment] 2015-07-23 02:41
Sorry for reopen the issue, but I want to know whether this probelm is solved, or it's genetic and can't be solved:
>> Even with synchronous calls I see the completion menu disappear/flicker with each new keypress. 

Many thanks.

**Comment by abingham** [comment] 2015-07-27 07:41
@zhuzhongshu As I understand things, this is not something we can fix.

**Comment by dgutov** [comment] 2018-02-11 21:32
For posterity: in current company-mode master, this problem is not exactly solved, but should only appear when the asynchronous calls complete slower than the user is typing.

Also please follow https://github.com/company-mode/company-mode/issues/337.

BTW @abingham I've never seen the flickering problem appear with synchronous backends. If you show an example, we'll probably be able to fix it.
