### ISSUE TITLE
Diagnostics not updated when deleting code.

### ISSUE THREAD

**Issue by r4nt** [abingham/emacs-ycmd#143] opened 2015-01-29 11:22 UTC
I often fix code by deleting random additional characters I somehow managed to get in. Is that a flycheck problem? STFW'ing hasn't enlightened me.

**Comment by abingham** [comment] 2015-02-01 07:35
Let me make sure I understand the problem. You've got some legitimate errors coming from ycmd which are displayed via flycheck. You make some corrective deletions and get the code into a state that no longer has the errors, but flycheck continues to indicate that the errors exist. Is that about right?

If so, my initial guess is that we're not asking ycmd for a reparse in a timely enough manner. flycheck-ycmd is pretty simple, and it just looks at the last available parse results to determine which errors exist. No matter what edits you make, if you don't trigger a reparse then you won't get updated information to flycheck.

You might futz with `ycmd-parse-conditions` and/or `ycmd-idle-change-delay` to see if that improves things for you.

**Comment by abingham** [comment] 2015-02-01 07:38
I can imagine more complex interactions between ycmd, flycheck, and buffer modification. For example, apropos to your case, we might a) watch for deletions in buffers b) see if those overlap with errors reported by ycmd, and c) remove/mask those overlapping errors from the report so that ycmd doesn't display them. Or maybe we trigger a reparse when overlap is detected (or when a certain volume of characters are deleted from error locations...something like that.)

**Comment by r4nt** [comment] 2015-02-01 09:39
I have the parse condition on 'idle-delay, so I assumed when I change the buffer a reparse is triggered. That works for when I insert text, but doesn't work when I just delete.

**Comment by ptrv** [comment] 2015-02-01 13:30
The condition `(not (eq beg end))` in `ycmd--on-change` returns `nil` when deleting a character because `beg` and `end` are equal. When implementing the function I added the condition because I thought it was triggered twice sometimes with same `beg` and `end` and wanted to avoid calling the function twice. I cannot reproduce this behavior anymore and therefore it can be removed. See #146 for the fix.

**Comment by abingham** [comment] 2015-02-01 16:28
I've merged in the change @ptrv submitted. @r4nt, if you can verify that this fixes the problem then I'll close this.

**Comment by r4nt** [comment] 2015-02-02 10:31
Works for me. Thanks!

**Closed** 2015-02-02 17:09 UTC
