### ISSUE TITLE
Directory completion issue

### ISSUE THREAD

**Issue by r4nt** [abingham/emacs-ycmd#162] opened 2015-03-16 13:32 UTC
I'm not sure whether this is a emacs-ycmd or company problem, so reporting this here first:
When completion paths in ycm, there are relevant completions, but when one of them is selected (by pressing enter), the whole path is replaced, leaving only the basename.

For example:
1. typing
./some/path/dir/
2. suggestions
file1
file2
3. selecting one of them by pressing enter
4. now the whole path (including the leading ./some/path/dir/) is replaced by
file1

(@Valloric fyi)

**Comment by ptrv** [comment] 2015-03-16 13:52
I cannot reproduce this with latest company, emacs-ycmd and ycmd. For me the file suggestion does not replace the whole path.

Do you have more details on the repro?

**Comment by r4nt** [comment] 2015-03-16 17:43
~ $ mkdir aaa
~ $ emacs hello.sh
In Emacs:

cd ~/a
   aaa -> [Dir]

{ press Enter or Tab }

cd aaa

(note the missing ~/, same works if you use /tmp or another dir)

**Comment by ptrv** [comment] 2015-03-16 18:05
@r4nt I could reproduce the issue with your example. However I am not able to reproduce it in a "regular ycmd" c++ project with a `.ycm_extra_conf.py` loaded.

**Comment by ptrv** [comment] 2015-03-16 19:29
I tried the reproduction steps also in a python buffer and I could not reproduce the bug. It seems it is filetype related.

**Comment by r4nt** [comment] 2015-03-17 08:36
Yes, this is for bash files. Any reason YCM shouldn't work for shell? (@Valloric)

**Comment by Valloric** [comment] 2015-03-17 18:04
No ideas, sorry.

**Comment by apresta** [comment] 2015-03-18 18:31
One more data point: these kind of path completions work fine in a normal text buffer (.txt), but not in a .sh file. Could it be that YCM is misconfigured just for this particular mode?

**Comment by apresta** [comment] 2015-03-25 16:31
It's also happening when editing my .emacs file.

**Comment by abingham** [comment] 2015-03-27 17:35
@apresta Are you seeing any suspicious-looking output in `*Messages*` when you see the bad behavior?

**Comment by apresta** [comment] 2015-03-27 17:40
Nothing in *Messages*. In *ycmd-server* I see "Received completion request" and "Using filetype completion: False", but nothing when I press Enter to accept the completion (triggering the problem).

**Comment by abingham** [comment] 2015-03-27 18:06
OK, thanks for checking. I'm looking into this right now, and I *think* I'm on the right trail. I'll let you know how it goes...

**Comment by abingham** [comment] 2015-03-27 18:21
It appears that we're ignoring ycmd's advice on where to put the completion result. Here's the HTTP traffic involved in one buggy completion:
```HTTP REQUEST CONTENT

"{\"file_data\":{\"\\/Users\\/sixtynorth\\/sandbox\\/ycmd\\/hello.sh\":{\"contents\":\"cd ~\\/san\\n\",\"filetypes\":[\"generic\"]}},\"filepath\":\"\\/Users\\/sixtynorth\\/sandbox\\/ycmd\\/hello.sh\",\"line_num\":1,\"column_num\":9}"
HTTP RESPONSE CONTENT

((completion_start_column . 6)
 (completions .
	      [((extra_menu_info . "[Dir]")
		(insertion_text . "sandbox"))
	       ((extra_menu_info . "[File]")
		(insertion_text . "passport 01.small.png"))
	       ((extra_menu_info . "[File]")
		(insertion_text . ".csearchindex"))]))
```
ycmd is clearly instructing us to start the completion at column 6 – which seems to absolutely correct – yet it's getting inserted at column 4.

Another related clue is that when we provide a prefix to company-mode via `company-ycmd--prefix`, we respond with the text starting at column 4, i.e. the `~/sa` portion of `cd ~/sa`.

**Comment by abingham** [comment] 2015-03-27 18:46
The problem seems to definitely be a mismatch between a) what we report to company-mode for the prefix and b) what ycmd returns for completion. The proximal culprit here in our case is `company-grab-symbol` which we use to determine the prefix. For example, if my cursor is at the end of this:
```
cd ~/sa
```
the prefix calculated by `company-grab-symbol` is `~/sa`. However, ycmd calculates candidates like `sandbox` and `salami` rather than `~/sandbox` and `~/salami` (which is a very important directory.) As a result, company is replacing the prefix with the candidates, and this results in the behavior we're seeing.

I'm not sure how to fix this yet. If I replace `company-grab-symbol` with `company-grab-word`, this specific problem goes away, but I'm not sure how it impacts other completions (i.e. in C++, etc.) With that said, I selected `company-grab-symbol` mostly because it sounded like the most official function to use...it doesn't have any documentation.

One possibility is that we can figure out how to "short-circuit" company mode and simply tell it to insert the completion at the offset supplied by ycmd. This would be great.

**Comment by dgutov** [comment] 2015-03-27 20:34
> With that said, I selected company-grab-symbol mostly because it sounded like the most official function to use...it doesn't have any documentation.

You're basically expected the read the source, and see if it corresponds to your expectations (and expectations of underlying technologies). The framework has no way of anticipating where completions returned by ycmd would start.

**Comment by abingham** [comment] 2015-03-27 23:00
@dgutov I wouldn't expect the framework to anticipate the completion insertion points, of course. However, in my case I have the insertion points in hand, and it would be convenient if I could communicate that to company.

**Comment by abingham** [comment] 2015-03-27 23:06
@apresta @r4nt I've pushed a change to [the `fix-prefix` branch](https://github.com/abingham/emacs-ycmd/tree/fix-prefix) that hopes to address the issue. Could you try it out and see if it helps? It definitely works in the limited testing I've done here.

The core problem is a mismatch between how company and ycmd determine where to insert completions. This change tries to reconcile that difference. It's a bit hacky (in ways I'm [trying to rectify](http://emacs.stackexchange.com/questions/10362/adding-text-properties-to-empty-strings)), but it seems to hobble along.

**Comment by dgutov** [comment] 2015-03-27 23:34
@abingham Why not use `(- (point (length prefix))` directly later, instead of saving the value to a property?

**Comment by abingham** [comment] 2015-03-27 23:49
That's a very good question. If there was a good reason for it, I don't remember it now. Probably just my being tired...I'll take care of that soon.

**Comment by dgutov** [comment] 2015-03-28 00:05
If there are cases when this fails, I'd like to know about them. Some other actions might get called from other positions in the buffer (like `annotation`, although that might be something to fix, too), but not `candidates`.

**Comment by abingham** [comment] 2015-03-30 06:44
The fix I put in place for this issue seems to be working fine, so I've merged it into `master` hereeffbc7a343551fe01614c1658551d4b21ede1a93. Let me know if you see any problems.

**Closed by abingham** 2015-03-30 06:44 UTC
Labels: bug
