### ISSUE TITLE
python issues? - goto, import statement completions, company popup formatting

### ISSUE THREAD

**Issue by DGalt** [abingham/emacs-ycmd#203] opened 2015-06-26 15:46 UTC
I'm trying to get emacs-ycmd up and running for my python development, and have gotten it working to a certain point, but there are some issues I've run in to. I'm not sure if some of these are specific to python support, or specific to how my system is set up (I'm on Arch using the global installs via pacman of python and python2, along with associated packages), or would be better directed at the devs of pycmd, jedi, company, etc. That being said...

**No completions on import statements.**
 E.g. `import date` will complete to `datetime` with other python completion packages such as jedi.el or anaconda-mode, but no suggestion is provided by emacs-ycmd. `import` itself does not complete until after being used at least once in a new file

similarly, there is no completion options given for importing submodules when using the formatting `from X import Y`
e.g. `from PyQt5 import ` would give me a list of PyQt5 modules available for import if using other completion packages, but I don't get anything using emacs-ycmd

**Company-tooltip formatting**
This may be a result of the fuzzy matching abilities of ycmd, so it may not be a bug at all, but often times the company tooltip that is generated is not respecting the formatting set by company-tooltip-common / company-tooltip-common-selection settings. 

Simple example: http://imgur.com/4xrKRHR

As more characters are entered, and matches are narrowed, the font should also change but generally doesn't when using emacs-ycmd for completions. 
This is certainly not a major issue, just odd because sometimes it works (i.e. the font changes appropriately) and sometimes it doesn't. 

**Trying to use Goto definition fails**
with Warning: `Warning (emacs): goto exception: Builtin modules cannot be displayed.` 

in `*ycmd-server*`:
```
Traceback (most recent call last):
  File "/home/dan/.ycmd/ycmd/third_party/bottle/bottle.py", line 861, in _handle
    return route.call(**args)
  File "/home/dan/.ycmd/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "/home/dan/.ycmd/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 100, in wrapper
    return callback( *args, **kwargs )
  File "/home/dan/.ycmd/ycmd/ycmd/../ycmd/hmac_plugin.py", line 62, in wrapper
    body = callback( *args, **kwargs )
  File "/home/dan/.ycmd/ycmd/ycmd/../ycmd/handlers.py", line 85, in RunCompleterCommand
    request_data ) )
  File "/home/dan/.ycmd/ycmd/ycmd/../ycmd/completers/python/jedi_completer.py", line 101, in OnUserCommand
    return self._GoTo( request_data )
  File "/home/dan/.ycmd/ycmd/ycmd/../ycmd/completers/python/jedi_completer.py", line 125, in _GoTo
    return self._BuildGoToResponse( definitions )
  File "/home/dan/.ycmd/ycmd/ycmd/../ycmd/completers/python/jedi_completer.py", line 153, in _BuildGoToResponse
    raise RuntimeError( 'Builtin modules cannot be displayed.' )
RuntimeError: Builtin modules cannot be displayed.
```

I've tried this with both standard-library and third-party modules, with similar result.

**Comment by abingham** [comment] 2015-06-27 09:03
For the first and third issues, I think these are related to `ycmd` itself (or possibly the `jedi` completer). As far as I can tell, `emacs-ycmd` faithfully displays any completions (and goto responses) that come from `ycmd`. And in fact we get completions for some imports, but apparently we're not getting any results for standard library packages.

@valloric: Does any of this ring any bells for you? Are there any known issues in `ycmd` for completing import statements?

**Comment by abingham** [comment] 2015-06-27 09:16
As for the tooltip formatting issue, I assume you mean that `company-ycmd` doesn't highlight the prefix. (If that's not what you mean, let me know!). I think this has to do with non-prefix-based matching. If you set `ycmd-enable-fuzzy-matching` to `nil`, do you get the behavior you expect?

**Comment by Valloric** [comment] 2015-06-27 16:19
You're trying to display completions for import statements of PyQt, which is a set of C++ binaries that implement the Python module API. They're not native Python modules, which is why Jedi is having problems with them. That's my best guess.

You might want to create a test case and report this on the Jedi issue tracker.

**Comment by DGalt** [comment] 2015-06-27 19:26
Well, this is an issue for the standard libraries too. For example `from glob import g` fails to provide any completion suggestions. I've tested these same scenarios (standard module import and third party modules) using Anaconda-mode, which is a different completion package for python in Emacs that also uses Jedi as its backend, and I get the appropriate completion suggestions. 

The GoTo traceback was also generated when looking for the definition for a standard library module

**Comment by DGalt** [comment] 2015-06-27 21:12
As for the tooltip formatting, abingham you're right that this is a result of the non-prefix based matching, which is what I suspected. It would be a nice feature, though, if even when fuzzy matching is enabled if the matched characters are highlighted (e.g. if I'm looking for `QPushButton` and I type in `qpb` then those mated characters are highlighted in the completion results - I know this is how it works in some IDEs like PyCharm that do fuzzy matching). This is feature request for company, though, so I'll bring it up over there.

**Comment by abingham** [comment] 2015-06-28 11:39
OK, great. It sounds like I can close this since I don't think the problems you're seeing have anything to do with `emacs-ycmd` directly. If that turns out to not be the case, though, feel free to re-open it.

**Closed by abingham** 2015-06-28 11:39 UTC

**Comment by DGalt** [comment] 2015-06-28 12:30
Sounds good, I'll open an issue with ycmd, unless there is a more appropriate place @valloric

**Comment by Valloric** [comment] 2015-06-29 20:21
@DGalt The appropriate place would be https://github.com/davidhalter/jedi

**Comment by DGalt** [comment] 2015-06-29 20:49
@Valloric I have no issues getting the correct completions using Anaconda-mode and/or Jedi.el (other python completion packages in Emacs - both of which use Jedi), which would imply the issue being in something other than Jedi, no?

**Comment by Valloric** [comment] 2015-06-29 21:06
Hm, could be a ycmd issue then. File a bug on ycmd's tracker; please create a reproducible test case so I can confirm the problem and track it down.

**Comment by abingham** [comment] 2015-06-30 07:13
@DGalt: It could potentially still be an `emacs-ycmd` issue, so please tag me on any bug you create in the ycmd tracker.
