### ISSUE TITLE
File mode specification error: (error "Server timeout.")

### ISSUE THREAD

**Issue by henry-y** [abingham/emacs-ycmd#215] opened 2015-09-09 02:50 UTC
Whenever I open a .c or .cpp source file, this error message pops. It seems ycmd doesn't work?

**Comment by abingham** [comment] 2015-09-09 06:06
Does it work for other file types, e.g. Python or Go (depending on how you compiled ycmd)?

**Comment by henry-y** [comment] 2015-09-22 05:25
@abingham no, it won't work for other file types either. I've found something recently:

when I'm login as root user on my virtual machine, there's no such error.
but when I'm working as a normal user on a remote machine, there is such error.

all ycmd and emacs-ycmd files are located at ~/.emacs.d, so I suppose there's no difference?

**Comment by jeaye** [comment] 2015-09-29 14:01
I'm getting this issue as well. @henry-y, were you able to resolve it?

**Comment by Alexander-Shukaev** [comment] 2015-11-06 02:58
I'm pretty sure that you guys are on Arch Linux or similar distribution which uses Python 3 as a default Python interpreter,  that is `python` is Python 3 rather than 2.  Typically, on such platforms to invoke Python 2, one has to explicitly use `python2`.  Hence,

```
(setq-default ycmd-server-command '("python2" ...))
```

**Comment by ptrv** [comment] 2016-07-31 22:49
Closing this issue since it was probably due to wrong python version.

Please re-open if the issue is still happening.

**Closed by ptrv** 2016-07-31 22:49 UTC
