### ISSUE TITLE
Support header only libraries

### ISSUE THREAD

**Issue by gnzlbg** [abingham/emacs-ycmd#218] opened 2015-10-16 12:35 UTC
I am using emacs-ycmd with a json compilation data base, and am not getting auto completion in headers (Im working on a header only library that has cpp files only for tests). I get errors of the type:

```
2015-10-16 14:26:39,741 - INFO - Adding buffer identifiers for file: /header_file.hpp
Traceback (most recent call last):
  File "ycmd/third_party/bottle/bottle.py", line 861, in _handle
    return route.call(**args)
  File "ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "ycmd/ycmd/../ycmd/watchdog_plugin.py", line 100, in wrapper
    return callback( *args, **kwargs )
  File "ycmd/ycmd/../ycmd/hmac_plugin.py", line 62, in wrapper
    body = callback( *args, **kwargs )
  File "ycmd/ycmd/../ycmd/handlers.py", line 71, in EventNotification
    event_handler )( request_data )
  File "ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 368, in OnFileReadyToParse
    raise ValueError( NO_COMPILE_FLAGS_MESSAGE )
ValueError: Still no compile flags, no completions yet.
```

and

```
2015-10-16 14:29:26,560 - ERROR - Exception from semantic completer (using general): Traceback (most recent call last):
  File "ycmd/ycmd/../ycmd/handlers.py", line 104, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/ycmd/ycmd/../ycmd/completers/completer.py", line 163, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "ycmd/ycmd/../ycmd/completers/completer.py", line 179, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 90, in ComputeCandidatesInner
    raise RuntimeError( NO_COMPILE_FLAGS_MESSAGE )
RuntimeError: Still no compile flags, no completions yet.
```

In ".cpp" files everything works as expected.

**Comment by ptrv** [comment] 2015-10-16 12:59
I think this is rather a `ycmd` issue rather than an `emacs-ycmd` one. Have you tried to specify the flags in `.ycm_extra_conf.py` manually instead of using the json compilation database?

@valloric What do you think?

**Comment by gnzlbg** [comment] 2015-10-16 16:19
I kind of got it to work by going through the compilation database collecting all the flags from all the files but I don't see a good solution here.

**Comment by abingham** [comment] 2015-10-18 17:07
As I understand things, @ptrv is right. This is a limitation/characteristic of ycmd. If you are using a header only library, then you won't have a compilation database so you have to provide the flags yourself. 

Some configs use a trick where they look for a header's associated implementation file and use those flags.

**Comment by Valloric** [comment] 2015-10-31 18:54
The root cause of this is, well, C++. Headers aren't compiled individually by compilers, only "real" source files (.cpp etc). Headers are merely included by them and thus indirectly compiled. So no build system tries to build command-line calls to produce object files for headers since that doesn't make any sense, so cmake won't have entries for headers in the compilation database.

Your best bet is to have your `ycm_extra_conf` file recognize that a file is a header and then produce some flags that are useful when trying to compile that; usually the best bet is to find the corresponding cpp file and use its flags.

**Comment by gnzlbg** [comment] 2015-10-31 22:27
This is basically what I'm doing right now. Scan all my cop files, "add"
their flags, and use the superset for headers :/

It's not perfect, but headache to "just works" ratio is pretty low.

**Comment by ptrv** [comment] 2016-03-12 16:14
Since this is not an `emacs-ycmd` issue, I close it.

**Closed by ptrv** 2016-03-12 16:14 UTC
